export interface FixedStar {
  name: string;
  bayerDesignation: string;
  sign: string;
  constellationName: string;
  tropicalDegree: string;
  magnitude: number;
  onEcliptic: boolean;
  interpretation: string;
}

export const FIXED_STARS: FixedStar[] = [
  {
    name: "Hamal",
    bayerDesignation: "α Ari",
    sign: "Aries",
    constellationName: "The Ram",
    tropicalDegree: "7 Taurus 40",
    magnitude: 2.0,
    onEcliptic: true,
    interpretation: "The brow of the Ram, Hamal is a star of blunt force and pioneering will. It grants drive, independence and the courage to strike first, yet its shadow is violence, impatience and a tendency to bruise others through sheer headlong momentum.",
  },
  {
    name: "Sheratan",
    bayerDesignation: "β Ari",
    sign: "Aries",
    constellationName: "The Ram",
    tropicalDegree: "3 Taurus 59",
    magnitude: 2.6,
    onEcliptic: true,
    interpretation: "One of the Ram's horns, Sheratan carries the bruising, combative energy of unrestrained physical force. It can confer protection and decisive action, but also marks danger through accident, conflict and the destructive misuse of one's own strength.",
  },
  {
    name: "Mesarthim",
    bayerDesignation: "γ Ari",
    sign: "Aries",
    constellationName: "The Ram",
    tropicalDegree: "",
    magnitude: 3.9,
    onEcliptic: false,
    interpretation: "The third horn-star of the Ram, set off the ecliptic, Mesarthim speaks of beginnings discovered and ground broken. It hints at the lonelier, off-stage labour behind first conquests, rewarding the patient discoverer while warning against pride in being first.",
  },
  {
    name: "Mirach",
    bayerDesignation: "β And",
    sign: "Aries",
    constellationName: "The Ram",
    tropicalDegree: "0 Taurus 24",
    magnitude: 2.1,
    onEcliptic: false,
    interpretation: "Though longitudinally near the Ram, Mirach sits far north in the Chained Maiden, a star of receptive beauty and devoted love. It draws fortunate marriages and the goodwill of others, yet its gift can curdle into passivity, waiting forever to be rescued rather than acting.",
  },
  {
    name: "Aldebaran",
    bayerDesignation: "α Tau",
    sign: "Taurus",
    constellationName: "The Bull",
    tropicalDegree: "9 Gemini 47",
    magnitude: 0.9,
    onEcliptic: true,
    interpretation: "The fiery red Eye of the Bull and a Royal Watcher of the heavens, Aldebaran promises honour, eloquence and high achievement won through integrity. Its gift is conditional: greatness endures only if one keeps faith with one's word, for compromise of integrity invites a swift and total fall.",
  },
  {
    name: "Pleiades (Alcyone)",
    bayerDesignation: "η Tau",
    sign: "Taurus",
    constellationName: "The Bull",
    tropicalDegree: "0 Gemini 00",
    magnitude: 2.9,
    onEcliptic: true,
    interpretation: "The weeping sisters of the Bull's shoulder, the Pleiades open vision both luminous and painful. They confer mystical insight, ambition and a sharp eye, but are traditionally tied to sorrow, weeping, and matters of sight, drawing the soul toward what is too bright to gaze upon directly.",
  },
  {
    name: "Algol",
    bayerDesignation: "β Per",
    sign: "Taurus",
    constellationName: "The Bull",
    tropicalDegree: "26 Taurus 10",
    magnitude: 2.1,
    onEcliptic: false,
    interpretation: "The Demon's Head held by Perseus, Algol is the most notorious of fixed stars, the unblinking Gorgon eye. It carries intense, concentrated passion and the power to either lose one's head or to seize collective rage and transmute it, a star of raw kundalini force that destroys the unready.",
  },
  {
    name: "Capulus",
    bayerDesignation: "M34 Per",
    sign: "Taurus",
    constellationName: "The Bull",
    tropicalDegree: "24 Taurus",
    magnitude: 5.5,
    onEcliptic: false,
    interpretation: "The sword-hand of Perseus, Capulus is a piercing, penetrating cluster off the ecliptic. It grants incisive, cutting force and ruthless effectiveness, but its shadow is brutality and a blade that wounds the innocent as readily as the foe.",
  },
  {
    name: "Pollux",
    bayerDesignation: "β Gem",
    sign: "Gemini",
    constellationName: "The Twins",
    tropicalDegree: "23 Cancer 13",
    magnitude: 1.1,
    onEcliptic: true,
    interpretation: "The mortal-turned-immortal twin, Pollux is the pugilist, fierce, courageous and cunning in the contest. It lends competitive brilliance and the will to win, yet carries a cruel, vindictive edge and danger linked to subtle poisons and ruthless rivalry.",
  },
  {
    name: "Castor",
    bayerDesignation: "α Gem",
    sign: "Gemini",
    constellationName: "The Twins",
    tropicalDegree: "20 Cancer 14",
    magnitude: 1.6,
    onEcliptic: true,
    interpretation: "The horseman twin, Castor is keen of mind and quick of tongue, gifted in writing, study and sudden insight. Its brilliance is mercurial and unstable, prone to nervous strain, sudden reversals of fortune, and trouble that arrives as swiftly as its inspirations.",
  },
  {
    name: "Sirius",
    bayerDesignation: "α CMa",
    sign: "Gemini",
    constellationName: "The Twins",
    tropicalDegree: "14 Cancer 05",
    magnitude: -1.4,
    onEcliptic: false,
    interpretation: "Far south of the ecliptic yet blazing as the brightest star of the sky, Sirius is the scorching Dog Star of sacred fire and burning ambition. It promises fame, honour and the heat of great success, but its brilliance can consume, scorching those who let ambition outrun their humanity.",
  },
  {
    name: "Bellatrix",
    bayerDesignation: "γ Ori",
    sign: "Gemini",
    constellationName: "The Twins",
    tropicalDegree: "20 Gemini 57",
    magnitude: 1.6,
    onEcliptic: false,
    interpretation: "The Amazon Star on the shoulder of Orion, north of the Twins' feet, Bellatrix is the female warrior, swift and forceful. It grants strategic boldness and outspoken courage, but warns of headlong rashness, accidents and the sudden ruin that follows reckless aggression.",
  },
  {
    name: "Asellus Borealis",
    bayerDesignation: "γ Cnc",
    sign: "Cancer",
    constellationName: "The Crab",
    tropicalDegree: "7 Leo 32",
    magnitude: 4.7,
    onEcliptic: true,
    interpretation: "The Northern Donkey beside the manger of the Crab, Asellus Borealis lends patient endurance, responsibility and the willingness to carry heavy burdens. Its steadiness can win quiet honour, yet it warns of recklessness with fire and the danger of being driven beyond one's strength.",
  },
  {
    name: "Acubens",
    bayerDesignation: "α Cnc",
    sign: "Cancer",
    constellationName: "The Crab",
    tropicalDegree: "13 Leo 38",
    magnitude: 4.3,
    onEcliptic: true,
    interpretation: "The sheltering Claw of the Crab, Acubens is a star of refuge, home and the instinct to protect. It grants steadfastness and the capacity to shield others, but its shadow turns to scheming, deceit and a grasping defensiveness that imprisons what it means to keep safe.",
  },
  {
    name: "Procyon",
    bayerDesignation: "α CMi",
    sign: "Cancer",
    constellationName: "The Crab",
    tropicalDegree: "25 Cancer 47",
    magnitude: 0.4,
    onEcliptic: false,
    interpretation: "The Lesser Dog rising before Sirius, set south of the Crab, Procyon promises sudden activity, swift rise and brilliant opportunity. Yet its fortune is volatile and impatient, giving fast success that can fade as quickly, rewarding initiative but punishing those who cannot sustain what they seized.",
  },
  {
    name: "Praesepe",
    bayerDesignation: "M44 Cnc",
    sign: "Cancer",
    constellationName: "The Crab",
    tropicalDegree: "7 Leo",
    magnitude: 3.7,
    onEcliptic: false,
    interpretation: "The Beehive cluster at the heart of the Crab, a misty cloud off the bright ecliptic line, Praesepe is the Manger of swarming, hidden things. It opens sensitivity to the unseen and to crowds, but traditionally clouds the eyes and the judgement, bringing fevered restlessness and a danger of being lost in the multitude.",
  },
  {
    name: "Regulus",
    bayerDesignation: "α Leo",
    sign: "Leo",
    constellationName: "The Lion",
    tropicalDegree: "29 Leo 50",
    magnitude: 1.4,
    onEcliptic: true,
    interpretation: "The Heart of the Lion and chief of the four Royal Stars, Regulus confers honour, ambition and the throne of leadership. Its kingship is conditional on nobility of conduct: success is dazzling but precarious, for any descent into revenge or dishonour topples the crown it bestowed.",
  },
  {
    name: "Denebola",
    bayerDesignation: "β Leo",
    sign: "Leo",
    constellationName: "The Lion",
    tropicalDegree: "21 Virgo 37",
    magnitude: 2.1,
    onEcliptic: true,
    interpretation: "The Tail of the Lion, Denebola is the contrarian star, gifting swift judgement, courage and the will to break with the established order. It can raise reformers and outsiders, but carries misfortune through disgrace, regret and the backlash that follows those who go against the grain.",
  },
  {
    name: "Zosma",
    bayerDesignation: "δ Leo",
    sign: "Leo",
    constellationName: "The Lion",
    tropicalDegree: "11 Virgo 19",
    magnitude: 2.6,
    onEcliptic: false,
    interpretation: "On the back of the Lion, north of the ecliptic, Zosma is the wounded healer and the victim who becomes redeemer. It grants depth, prophetic feeling and an instinct for the suffering of others, yet warns of melancholy, fear of poison, and the danger of carrying burdens not one's own.",
  },
  {
    name: "Alphard",
    bayerDesignation: "α Hya",
    sign: "Leo",
    constellationName: "The Lion",
    tropicalDegree: "27 Leo 17",
    magnitude: 2.0,
    onEcliptic: false,
    interpretation: "The solitary Heart of the Water-Serpent, lying south beneath the Lion, Alphard is a star of intense feeling and lonely power. It grants passion, knowledge of human nature and artistic force, but its shadow is uncontrolled emotion, excess and a venom that can poison the self through immoderation.",
  },
  {
    name: "Vindemiatrix",
    bayerDesignation: "ε Vir",
    sign: "Virgo",
    constellationName: "The Maiden",
    tropicalDegree: "9 Libra 56",
    magnitude: 2.8,
    onEcliptic: true,
    interpretation: "The Grape-Gatherer in the wing of the Maiden, Vindemiatrix is the star of harvest and of the widow. It grants focus, persistence and skill in collecting the fruits of long labour, yet carries a melancholy of loss, faulty judgement in haste, and the trial of standing alone after others depart.",
  },
  {
    name: "Zaniah",
    bayerDesignation: "η Vir",
    sign: "Virgo",
    constellationName: "The Maiden",
    tropicalDegree: "4 Libra 53",
    magnitude: 3.9,
    onEcliptic: true,
    interpretation: "A refined star in the wing of the Maiden, Zaniah breathes courtesy, order and gentle concord. It favours scholarship, congenial company and harmonious relations, drawing honour through grace rather than force, though its softness can shrink from the conflict that real change requires.",
  },
  {
    name: "Spica",
    bayerDesignation: "α Vir",
    sign: "Virgo",
    constellationName: "The Maiden",
    tropicalDegree: "23 Libra 50",
    magnitude: 1.0,
    onEcliptic: false,
    interpretation: "The Ear of Wheat held by the Maiden, lying just south of the ecliptic, Spica is among the most fortunate of all stars, a beacon of gifts, brilliance and protection. It promises talent, fame and unexpected good fortune, the radiant grace that shelters its natives even in adversity.",
  },
  {
    name: "Alkaid",
    bayerDesignation: "η UMa",
    sign: "Virgo",
    constellationName: "The Maiden",
    tropicalDegree: "27 Virgo 00",
    magnitude: 1.9,
    onEcliptic: false,
    interpretation: "The tip of the Great Bear's tail, far north over the Maiden, Alkaid is the Mourners' Star and a point of profound destructive-creative power. It marks those who handle crisis, endings and matters of life and death, conferring force and consequence but exposing its natives to sorrow and danger.",
  },
  {
    name: "Zubeneschamali",
    bayerDesignation: "β Lib",
    sign: "Libra",
    constellationName: "The Scales",
    tropicalDegree: "19 Scorpio 22",
    magnitude: 2.6,
    onEcliptic: true,
    interpretation: "The Northern Scale, the higher pan of the balance, Zubeneschamali is the more fortunate beam, promising good fortune, high ambition and lasting honour. It rewards just measure and social good, lifting those who serve fair causes, though it asks that the gift be repaid in genuine fairness.",
  },
  {
    name: "Zubenelgenubi",
    bayerDesignation: "α Lib",
    sign: "Libra",
    constellationName: "The Scales",
    tropicalDegree: "15 Scorpio 05",
    magnitude: 2.8,
    onEcliptic: true,
    interpretation: "The Southern Scale, the lower pan once called the unfortunate claw, Zubenelgenubi weighs the cost of every choice. It can bring trials, loss and the price of imbalance, yet to those who face the reckoning honestly it grants hard-won justice and the strength forged by adversity.",
  },
  {
    name: "Arcturus",
    bayerDesignation: "α Boo",
    sign: "Libra",
    constellationName: "The Scales",
    tropicalDegree: "24 Libra 14",
    magnitude: -0.05,
    onEcliptic: false,
    interpretation: "The Bear-Guardian blazing high north of the Scales, Arcturus is a pathfinder star of prosperity through self-determination. It grants fame, riches and the pioneering courage to forge a new way, rewarding the trailblazer who keeps to a just path while punishing arrogant overreach.",
  },
  {
    name: "Izar",
    bayerDesignation: "ε Boo",
    sign: "Libra",
    constellationName: "The Scales",
    tropicalDegree: "28 Libra",
    magnitude: 2.4,
    onEcliptic: false,
    interpretation: "A beautiful double in the Herdsman, set north of the Scales, Izar fuses contrasting natures into a single bright point. It speaks of partnership, refinement and the art of bringing opposites into accord, granting charm and grace while warning against vanity in beauty.",
  },
  {
    name: "Antares",
    bayerDesignation: "α Sco",
    sign: "Scorpio",
    constellationName: "The Scorpion",
    tropicalDegree: "9 Sagittarius 46",
    magnitude: 1.1,
    onEcliptic: true,
    interpretation: "The fiery red Heart of the Scorpion and the fourth Royal Watcher, Antares is the rival of Mars, a star of ferocious courage, intensity and headlong passion. It grants the power to face death and transformation, but its shadow is obsession, self-destruction and the recklessness that consumes its own honour.",
  },
  {
    name: "Acrab",
    bayerDesignation: "β Sco",
    sign: "Scorpio",
    constellationName: "The Scorpion",
    tropicalDegree: "3 Sagittarius 11",
    magnitude: 2.6,
    onEcliptic: true,
    interpretation: "The forehead of the Scorpion, Acrab (Graffias) is a star of crisis, danger and sudden malefic force. It confers intensity and the capacity to wield power in extremity, yet warns of pestilence, sudden loss and the destructive turn of events that test the soul's resilience.",
  },
  {
    name: "Alphecca",
    bayerDesignation: "α CrB",
    sign: "Scorpio",
    constellationName: "The Scorpion",
    tropicalDegree: "12 Scorpio 18",
    magnitude: 2.2,
    onEcliptic: false,
    interpretation: "The jewel of the Northern Crown, set north of the Scorpion, Alphecca is the gift of honour, dignity and artistic or poetic grace. It confers a quiet nobility and the love of others, a crown bestowed by merit, though it warns that betrayal in love can tarnish even the brightest reward.",
  },
  {
    name: "Dschubba",
    bayerDesignation: "δ Sco",
    sign: "Scorpio",
    constellationName: "The Scorpion",
    tropicalDegree: "2 Sagittarius 34",
    magnitude: 2.3,
    onEcliptic: false,
    interpretation: "The crown of the Scorpion's forehead, lying off the bright ecliptic path, Dschubba is a star of research, leadership and concentrated intensity. It draws those who probe forbidden or hidden depths, granting authority in dark or difficult matters while exposing them to treachery and entanglement.",
  },
  {
    name: "Galactic Center",
    bayerDesignation: "—",
    sign: "Sagittarius",
    constellationName: "The Archer",
    tropicalDegree: "27 Sagittarius 00",
    magnitude: 0,
    onEcliptic: true,
    interpretation: "The deep heart of our galaxy, lying on the ecliptic in the Archer, the Galactic Center is a point of vast, impersonal power and cosmic perspective. Contact with it can confer extraordinary reach, vision and influence, dissolving the small self into something larger, yet it can overwhelm those unready for so great a current.",
  },
  {
    name: "Acumen",
    bayerDesignation: "M7 Sco",
    sign: "Sagittarius",
    constellationName: "The Archer",
    tropicalDegree: "28 Sagittarius",
    magnitude: 3.3,
    onEcliptic: true,
    interpretation: "The sting-cluster of the Scorpion's tail spilling into the Archer, Acumen is a nebulous star linked to lasting wounds and weakened sight. Traditionally maleficent, it marks pain that endures and slanders that scar, yet through such trials it can sharpen perception and forge hard-won wisdom.",
  },
  {
    name: "Facies",
    bayerDesignation: "M22 Sgr",
    sign: "Sagittarius",
    constellationName: "The Archer",
    tropicalDegree: "8 Capricorn",
    magnitude: 5.1,
    onEcliptic: false,
    interpretation: "The Face of the Archer, a cluster set off the ecliptic line, Facies is among the more violent of fixed stars, tied to ruthless focus and the leader who sees only the target. It grants piercing concentration and the power to command, but its shadow is blindness, accident and a precision turned cruel.",
  },
  {
    name: "Rukbat",
    bayerDesignation: "α Sgr",
    sign: "Sagittarius",
    constellationName: "The Archer",
    tropicalDegree: "15 Capricorn",
    magnitude: 3.9,
    onEcliptic: false,
    interpretation: "The Knee of the Archer, set south of the ecliptic, Rukbat is the stable foundation that steadies the bow. It grants firmness, endurance and a steadfast base from which to aim high, the quiet strength beneath ambition, warning only against rigidity that cannot bend.",
  },
  {
    name: "Deneb Algedi",
    bayerDesignation: "δ Cap",
    sign: "Capricorn",
    constellationName: "The Sea-Goat",
    tropicalDegree: "23 Aquarius 33",
    magnitude: 2.9,
    onEcliptic: true,
    interpretation: "The Tail of the Sea-Goat, Deneb Algedi is a star of just law and beneficent power wielded with mercy. It grants the authority of the wise lawgiver and protection in matters of justice, bringing both blessing and reckoning, fortune to the upright and consequence to the corrupt.",
  },
  {
    name: "Nashira",
    bayerDesignation: "γ Cap",
    sign: "Capricorn",
    constellationName: "The Sea-Goat",
    tropicalDegree: "21 Aquarius 46",
    magnitude: 3.7,
    onEcliptic: true,
    interpretation: "The Bringer of Good Tidings in the tail of the Sea-Goat, Nashira is the fortunate star that overcomes evil through perseverance. It promises eventual triumph over obstacles and the favour that follows steadfast integrity, the reward earned by those who hold their course against difficulty.",
  },
  {
    name: "Altair",
    bayerDesignation: "α Aql",
    sign: "Capricorn",
    constellationName: "The Sea-Goat",
    tropicalDegree: "1 Aquarius 47",
    magnitude: 0.8,
    onEcliptic: false,
    interpretation: "The Flying Eagle soaring north of the Sea-Goat, Altair is a star of bold ambition, daring and swift, decisive action. It confers courage, command and the will to rise high, rewarding the audacious leader, though its shadow is hardness, ruthlessness and a flight that scorns those left below.",
  },
  {
    name: "Dabih",
    bayerDesignation: "β Cap",
    sign: "Capricorn",
    constellationName: "The Sea-Goat",
    tropicalDegree: "4 Aquarius",
    magnitude: 3.1,
    onEcliptic: false,
    interpretation: "The Slaughterer's Star on the head of the Sea-Goat, set off the ecliptic, Dabih counsels caution, reserve and mistrust of easy trust. It grants positions of authority and the wealth of patient prudence, but warns of loss through misplaced confidence and the suspicion that isolates the guarded soul.",
  },
  {
    name: "Sadalmelik",
    bayerDesignation: "α Aqr",
    sign: "Aquarius",
    constellationName: "The Water-Bearer",
    tropicalDegree: "3 Pisces 31",
    magnitude: 3.0,
    onEcliptic: true,
    interpretation: "The Lucky Star of the King in the shoulder of the Water-Bearer, Sadalmelik pours out idealism, vision and the wish to better the human lot. It favours those who serve the collective good and the imaginative reformer, yet warns of persecution, sudden loss, and ideals that overwhelm practical life.",
  },
  {
    name: "Sadalsuud",
    bayerDesignation: "β Aqr",
    sign: "Aquarius",
    constellationName: "The Water-Bearer",
    tropicalDegree: "23 Aquarius 24",
    magnitude: 2.9,
    onEcliptic: true,
    interpretation: "The Luckiest of the Lucky, in the shoulder of the Water-Bearer, Sadalsuud is a star of fortunate change, new beginnings and the breaking of old constraints. It heralds renewal, gifts won through originality and the favour that comes when one releases the past to embrace a wider future.",
  },
  {
    name: "Fomalhaut",
    bayerDesignation: "α PsA",
    sign: "Aquarius",
    constellationName: "The Water-Bearer",
    tropicalDegree: "3 Pisces 52",
    magnitude: 1.2,
    onEcliptic: false,
    interpretation: "The Mouth of the Southern Fish drinking the Water-Bearer's stream, a Royal Watcher far south of the ecliptic, Fomalhaut is the star of high ideals and spiritual aspiration. It promises fame and magical or mystical gift, conditional on purity of purpose, for ideals turned to selfish ends curdle into their opposite.",
  },
  {
    name: "Albali",
    bayerDesignation: "ε Aqr",
    sign: "Aquarius",
    constellationName: "The Water-Bearer",
    tropicalDegree: "12 Aquarius",
    magnitude: 3.8,
    onEcliptic: false,
    interpretation: "The Swallower in the stream of the Water-Bearer, set off the bright ecliptic, Albali is an ambivalent star of fortune mixed with danger. It can bring fortune and the favour of fate, yet hides a swallowing undertow, warning that what is given freely may also be taken back without warning.",
  },
  {
    name: "Alrescha",
    bayerDesignation: "α Psc",
    sign: "Pisces",
    constellationName: "The Water Barrier",
    tropicalDegree: "29 Aries 23",
    magnitude: 3.8,
    onEcliptic: true,
    interpretation: "The Knot binding the two Fishes of the Water Barrier, Alrescha is the star of union, of holding opposing currents together by a single cord. It grants the power to reconcile and to bind disparate forces into one purpose, yet warns that the knot, once strained, can bring entanglement and the struggle to break free.",
  },
  {
    name: "Fum al Samakah",
    bayerDesignation: "β Psc",
    sign: "Pisces",
    constellationName: "The Water Barrier",
    tropicalDegree: "23 Pisces",
    magnitude: 4.5,
    onEcliptic: true,
    interpretation: "The Mouth of the Fish in the Water Barrier, Fum al Samakah is a quiet, receptive star of intuition and yielding sensitivity. It opens the soul to currents unseen and confers a gentle, devotional nature, but its passivity can drift, swallowing the will in dreams unless anchored by purpose.",
  },
  {
    name: "Markab",
    bayerDesignation: "α Peg",
    sign: "Pisces",
    constellationName: "The Water Barrier",
    tropicalDegree: "23 Pisces 29",
    magnitude: 2.5,
    onEcliptic: false,
    interpretation: "The Saddle of the Winged Horse, set high north of the Fishes, Markab is a star of steadfast endurance and the long, hard journey carried through. It grants stamina, return from danger and honour won by perseverance, but warns of grief, accident by fire or blade, and the cost of relentless toil.",
  },
  {
    name: "Scheat",
    bayerDesignation: "β Peg",
    sign: "Pisces",
    constellationName: "The Water Barrier",
    tropicalDegree: "29 Pisces 22",
    magnitude: 2.4,
    onEcliptic: false,
    interpretation: "The Leg of the Winged Horse, set north over the Water Barrier, Scheat is a star of imagination shadowed by misfortune, traditionally tied to danger from water and the drowning of hopes. It grants deep intuition and creative vision, yet warns of extreme bad luck, accident and the undertow of despair for those who lose their footing.",
  },
];

export function fixedStarSlug(name: string): string {
  return name.toLowerCase().replace(/[^a-z0-9]+/g, '-');
}

export function starLongitudeAtJD(star: FixedStar, _jd?: number): number {
  // Parse tropical degree string like "7 Taurus 40" → decimal longitude
  const SIGN_OFFSETS: Record<string, number> = {
    'Aries': 0, 'Taurus': 30, 'Gemini': 60, 'Cancer': 90, 'Leo': 120, 'Virgo': 150,
    'Libra': 180, 'Scorpio': 210, 'Sagittarius': 240, 'Capricorn': 270, 'Aquarius': 300, 'Pisces': 330,
  };
  if (!star.tropicalDegree) return 0;
  const parts = star.tropicalDegree.split(' ');
  if (parts.length < 2) return 0;
  const deg = parseFloat(parts[0]) || 0;
  const sign = parts[1];
  const min = parseFloat(parts[2]) || 0;
  return (SIGN_OFFSETS[sign] ?? 0) + deg + min / 60;
}

export function findStarConjunctions(
  chart: Record<string, { longitude: number; name: string }>,
  _jd: number,
  orb = 1.5
): StarConjunction[] {
  const results: StarConjunction[] = [];
  for (const [planetKey, planet] of Object.entries(chart)) {
    if (typeof planet?.longitude !== 'number') continue;
    for (const star of FIXED_STARS) {
      const starLon = starLongitudeAtJD(star);
      if (!starLon) continue;
      const diff = Math.abs(planet.longitude - starLon) % 360;
      const orbActual = Math.min(diff, 360 - diff);
      if (orbActual <= orb) {
        results.push({ star, planet: planetKey, orb: orbActual, longitude: planet.longitude });
      }
    }
  }
  return results;
}

export interface StarConjunction {
  star: FixedStar;
  planet: string;
  orb: number;
  longitude: number;
}
