export interface SphereCard {
  planet: string;
  sphereName: string;
  epithet: string;
  hierarchy: string;
  hierarchySub: string;
  bodyMember: string;
  bodyMemberSub: string;
  sense: string;
  senseSub: string;
  organ: string;
  metal: string;
  luciferic: string;
  ahrimanic: string;
  narrative: string;
}

export const SPHERES: Record<string, SphereCard> = {
  "sun": {
    planet: "Sun",
    sphereName: "Sun sphere",
    epithet: "Realm of the I · Organizer of Individuality",
    hierarchy: "Exusiai",
    hierarchySub: "Spirits of Form",
    bodyMember: "The I (Ego)",
    bodyMemberSub: "Consciousness Soul",
    sense: "",
    senseSub: "",
    organ: "Heart · Blood system",
    metal: "Gold · Aurum",
    luciferic: "Solar inflation — the I convinced of its own cosmic indispensability; grandiosity; solar fire without Saturn's structural demand. The messianic identification.",
    ahrimanic: "I-force reduced to achievement and function; spiritual organizing impulse flattened into career; identity dissolved into institutional role. The I that measures its worth.",
    narrative: "Bestowed the I upon humanity during the Lemurian epoch. The organizing center of ego-formation — where individuality receives its cosmic stamp. Steiner: \"the Sun is the conductor of the planetary system, standing between the liberating and destiny-determining spheres.\"",
  },
  "moon": {
    planet: "Moon",
    sphereName: "Moon sphere",
    epithet: "Closest Gate · Carrier of Soul Memory",
    hierarchy: "Angeloi",
    hierarchySub: "Angels",
    bodyMember: "Etheric body",
    bodyMemberSub: "Sentient Soul's habitual life",
    sense: "",
    senseSub: "",
    organ: "Brain · Reproductive system",
    metal: "Silver · Argentum",
    luciferic: "Soul inflated by its own past — identifying with accumulated emotional patterns as the self; escapism into ancestral memory; refusing to grow beyond emotional comfort",
    ahrimanic: "Lunar feeling-life mechanized or suppressed; genuine soul nourishment denied in favor of productivity; the past severed rather than understood and honored",
    narrative: "Each human being is accompanied across incarnations by a guardian Angel. The Moon-sphere holds accumulated soul-memory from prior lives and shapes the etheric body at birth. \"Fortress in the universe that preserves original wisdom once taught to primeval humanity.\"",
  },
  "mercury": {
    planet: "Mercury",
    sphereName: "Mercury sphere",
    epithet: "Realm of Mediation · Nerve-Sense Formation",
    hierarchy: "Archangeloi",
    hierarchySub: "Archangels",
    bodyMember: "Intellectual Soul",
    bodyMemberSub: "nerve-sense organization in its communicative dimension",
    sense: "",
    senseSub: "",
    organ: "Lungs · Respiratory system",
    metal: "Quicksilver · Mercurius",
    luciferic: "Thinking inflated into cleverness — speed substitutes for depth; the mind talks past the truth; facility mistaken for genuine insight; wit without substance",
    ahrimanic: "Thinking hardened into analysis that cannot perceive living reality; concepts become dead counters; the Ahrimanic intellect at its most characteristic expression. GA 13: \"Ahriman conceals the spiritual world that would appear behind sense-perception.\"",
    narrative: "Coordinates human thinking and folk-soul intelligence. \"Masters of coordinative knowledge\" reside here. Shapes the personality's temporal character and the cognitive signature the soul carries into incarnation. Michael's own sphere before his elevation to Archai.",
  },
  "venus": {
    planet: "Venus",
    sphereName: "Venus sphere",
    epithet: "Realm of Relation · Harmonization of Soul",
    hierarchy: "Dynamis",
    hierarchySub: "Spirits of Motion · Mights",
    bodyMember: "Astral body (harmonizing)",
    bodyMemberSub: "Sentient Soul's love-capacity",
    sense: "",
    senseSub: "",
    organ: "Kidneys · Filtration",
    metal: "Copper · Cuprum",
    luciferic: "Love inflated into idealization or dissolution of self in the beloved; the I losing its center in relationship; beauty as consolation rather than genuine spiritual practice",
    ahrimanic: "Relational life reduced to transaction; love calculated; beauty traded as status; the feeling life governed entirely by what can be measured or gained",
    narrative: "Governs the development of the astral body's love-capacity. \"Venus gazes deeply into the human heart rather than reflecting the outer universe, transforming soul secrets into dream-pictures.\" The sphere of harmonization — Dynamis bestow Cosmic Movement and the forces of moral warmth.",
  },
  "mars": {
    planet: "Mars",
    sphereName: "Mars sphere",
    epithet: "Realm of Will · Speech · Initiating Force",
    hierarchy: "Archangeloi",
    hierarchySub: "Archangels (Mars stream)",
    bodyMember: "Astral body (will dimension)",
    bodyMemberSub: "physical body's force of movement",
    sense: "",
    senseSub: "",
    organ: "Gall bladder · Bile",
    metal: "Iron · Ferrum",
    luciferic: "Will inflated into aggression or conquest; drive losing its moral direction; the burning of what cannot be rebuilt; passion substituting for genuine purposeful courage",
    ahrimanic: "Will hardened into cold strategic force — executes without feeling; treats other human beings as instruments; force without the warmth that would make it serve spirit rather than mechanism",
    narrative: "Provides the impulse for speech and movement. \"Mars is a liberating sphere — grants humanity freedom in the realm of speech.\" The sphere's individual spirit is that of a \"Talker\" that constantly communicates cosmic data to the rest of the planetary system. Will-force as initiating power.",
  },
  "jupiter": {
    planet: "Jupiter",
    sphereName: "Jupiter sphere",
    epithet: "Realm of Wisdom · Cosmic Understanding",
    hierarchy: "Kyriotetes",
    hierarchySub: "Spirits of Wisdom · Dominions",
    bodyMember: "Etheric body (wisdom-forming)",
    bodyMemberSub: "Intellectual Soul's highest development",
    sense: "",
    senseSub: "",
    organ: "Liver · Metabolic intelligence",
    metal: "Tin · Stannum",
    luciferic: "Wisdom inflated into hubris; the I convinced of its philosophical completeness; the teacher who has stopped learning; expansion beyond what has actually been earned through development",
    ahrimanic: "Wisdom reduced to data and system accumulation; living spiritual content replaced by information management; the capacity for genuine insight replaced by encyclopedic erudition",
    narrative: "\"Thinkers\" — imbue human thought with spiritual insight and light-filled, mobile concepts. Once breathed the etheric body into the human form on Old Sun. Jupiter \"helps the soul take wisdom into itself, often solving problems through the grace of free thinking while the human being sleeps.\" The sphere of cosmic largesse.",
  },
  "saturn": {
    planet: "Saturn",
    sphereName: "Saturn sphere",
    epithet: "Outermost Threshold · Karmic Crystallization",
    hierarchy: "Archai",
    hierarchySub: "Spirits of Personality · Time Spirits",
    bodyMember: "Physical body's structure",
    bodyMemberSub: "the I's karmic crystallization in form",
    sense: "",
    senseSub: "",
    organ: "Spleen · Bones · Skin",
    metal: "Lead · Plumbum",
    luciferic: "Saturn's structural demands avoided through spiritual bypass; karma spiritualized away rather than worked through; false transcendence of what Saturn is genuinely asking. The retreat into \"higher perspectives\" that avoids the biographical weight.",
    ahrimanic: "Structure hardened into compulsion; the I imprisoned by its limitations; karmic configuration mistaken for unalterable fate; the threshold becoming a permanent wall rather than a doorway to be earned through",
    narrative: "Preservers of cosmic memory — \"the living historian of the planetary system.\" Saturn holds the boundary of the classical cosmos; the soul passes through this outermost threshold carrying its karmic configuration most heavily inscribed. The Akashic domain in concentrated form.",
  },
  "uranus": {
    planet: "Uranus",
    sphereName: "Uranus sphere",
    epithet: "Higher Octave of Mercury · Awakening Force",
    hierarchy: "",
    hierarchySub: "",
    bodyMember: "",
    bodyMemberSub: "",
    sense: "",
    senseSub: "",
    organ: "",
    metal: "",
    luciferic: "Disruption for its own sake; destroying every framework before earning what would replace it; spiritual revolution as avoidance of the more demanding work of genuine development",
    ahrimanic: "The awakening force suppressed; the I conforming to outdated structures; collective evolutionary necessity denied in favor of rigid institutional belonging and the security of dead forms",
    narrative: "Force of primordial awakening; shatters crystallized forms to make way for what evolution requires. Steiner treats Uranus as a higher octave of Mercury — spiritualized intellect, thinking liberated from the cosmic intelligence into individual freedom. The Spirit-Self's awakening impulse at the collective level.",
  },
  "neptune": {
    planet: "Neptune",
    sphereName: "Neptune sphere",
    epithet: "Higher Octave of Venus · Dissolution & Spiritual Longing",
    hierarchy: "",
    hierarchySub: "",
    bodyMember: "",
    bodyMemberSub: "",
    sense: "",
    senseSub: "",
    organ: "",
    metal: "",
    luciferic: "Spiritual longing as escapism; the I fleeing incarnation into mystical vagueness; idealizing dissolution as spiritual achievement; Neptune confusion mistaken for genuine Imagination",
    ahrimanic: "Neptune's spiritual porosity armored against; the I closed to any experience that cannot be controlled or predicted; the mystical capacity systematically suppressed in the name of measurable results",
    narrative: "Oceanic dissolution and mystical compassion; forces standing beyond the classical solar order; boundary-dissolving intelligence working through sacred imagination and spiritual yearning. Higher octave of Venus — platonic, ideal love that seeks union beyond personal relation.",
  },
  "pluto": {
    planet: "Pluto",
    sphereName: "Pluto sphere",
    epithet: "Death-Regeneration Force · Collective Fate",
    hierarchy: "",
    hierarchySub: "",
    bodyMember: "",
    bodyMemberSub: "",
    sense: "",
    senseSub: "",
    organ: "",
    metal: "",
    luciferic: "Plutonic transformation as compulsion — the I seized by forces of destruction it mistakes for spiritual initiation; depth and destruction confused; the underworld as permanent identity rather than a passage",
    ahrimanic: "Pluto's power reduced to control — the I using depth-force to dominate rather than to genuinely transform; the underworld as a source of leverage rather than a domain of genuine regeneration",
    narrative: "The most primordial and compressed of cosmic forces — the intelligence of absolute transformation at the level of death and regeneration within entire evolutionary cycles. Works at the level of collective fate; does not negotiate; the force through which what must die finally can no longer be maintained.",
  },
};

export const SPHERE_ORDER = ['sun','moon','mercury','venus','mars','jupiter','saturn'] as const;
export type SphereKey = typeof SPHERE_ORDER[number];
